displayName: JWT Middleware Optional
type: middleware
import: github.com/savyjs/traefik-jwt-introspector
summary: 'Verify JWT token in auth header, optional mode, inject payload, and support host-based realm mapping'

testData:
  encodedHeader:
    - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ._XEngvIuxOcA-j7y_upRUbXli4DLToNf7HxH1XNmxSc"
