displayName: JWT Middleware Optional
type: middleware
import: github.com/savyjs/traefik-jwt-introspector
summary: 'Verify JWT token in auth header, optional mode, inject payload, and support host-based realm mapping'

testData:
  optional: true
  logLevel: none
  defaultRealm: example
  originRealmMap:
    example.com: example
    localhost: example
    127.0.0.1: example
  realms:
    - realmName: example
      clientId: client-id
      clientSecret: client-secret
      validateAPIUrl: http://example.com/realms/example/protocol/openid-connect/token/introspect
